id: 592382bd175643669f99faa643fda31e
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_267-Calling_Witness_with_a_Hundred_Prostrations-v1
  language: en
  author: ''
  volume: {}
